### MATH 6388: Statistical and Machine Learning, Fall 2022 
### Homework 2 

### Problem 1
In this problem, we create a small one-dimensional NumPy array. 

In [1]:
import numpy as np 
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

Form a new array called arr1, where every element is greater than 2. 

In [2]:
arr1 = arr[arr > 2]
arr1

array([3, 4, 5, 6, 7, 8])

Using arr1, form a new array called arr2, where every element is less than 5. 

In [3]:
arr2 = arr1[arr1 < 5]
arr2

array([3, 4])

How can we find elements of arr between 2 and 5 by combining the two conditions? 
You can look at the documentation page for numpy.logical_and


We can find the elements of arr between 2 & 5 by combining the two previous conditions via an addition sign. 

In [4]:
arr_between = arr[(arr > 2) & (arr < 5)]
arr_between

array([3, 4])

Let us convert the original NumPy array called arr to a valid probability mass function (pmf) that we will use later. 
You need to find a ''normalization'' constant such that the sum of elements in pmf must equal to 1. You don't need to be worried about negative values in this problem. 


In [5]:
arr_prob = np.ones(8)*(1/8)
arr_prob

array([0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125])

One common task in data analysis, statistics, and machine learning is taking random samples of data according to a given probability distribution. There are multiple ways to do so in NumPy, including numpy.random.choice. Generate a random sample from np.arange(5,45,5) of size 3 without replacement according to the pmf that you found in the previous experiment. 

In [6]:
a = np.arange(5, 45, 5)
a

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [7]:
np.random.choice(a, 3, replace = False, p = arr_prob)

array([40,  5, 30])

### Problem 2
In this problem, we want to implement the *softmax function*, often used as the last activation function of a neural network for multi-class classification problems (we will discuss what an activation function is later, but for now it is a function). In simple terms, the softmax function is a function that turns a vector of $C$ real values (positive or negative) into a vector of $C$ non-negative real values that sum to 1 (so the output will be a probability mass function or pmf). To be concrete, here is its definition when the input is $\mathbf{z}=[z_1,\ldots,z_C]\in\mathbb{R}^C$:

$$\sigma(\mathbf{z})_i=\frac{e^{z_i}}{\sum_{i=1}^Ce^{z_i}},\;i=1,\ldots,C$$

In the following cell, define and implement the softmax fuction (name of this function should be ''softmax'').

In [8]:
import numpy as np 
import math

def softmax(z):
    e = np.exp(z)
    return e / e.sum()

Compute the output of the softmax function for the following input vector.

In [9]:
z1 = np.array([5, 6, 11, 7])
softmax(z1)

array([0.00241233, 0.00655741, 0.97320538, 0.01782488])

Compute the output of the softmax function for the following input vector.

In [10]:
z2 = np.array([1e3, 1e4, 2e4])
softmax(z2) 

C:\Users\12563\AppData\Local\Temp/ipykernel_23512/2266792566.py:5: RuntimeWarning: overflow encountered in exp
  e = np.exp(z)
C:\Users\12563\AppData\Local\Temp/ipykernel_23512/2266792566.py:6: RuntimeWarning: invalid value encountered in true_divide
  return e / e.sum()


array([nan, nan, nan])

You probably noticed that something went wrong and there was an overflow in the exponentials. One way to get around this problem is to multiply both numerator and denominator by $e^{-z_{max}}$, where $z_{max}=\max_{i}z_i$. Implement this new function and name it as ''softmax_stable''. Once you defined this function, apply it to the two arrays z1 and z2. 

In [11]:
def softmax_stable(z):
    z_max = np.max(z)
    print(z_max)
    num = np.exp(z-z_max)
    print(num)
    denom = np.sum(np.exp(z-z_max))
    ans = (num / denom) 
    return ans

print(softmax_stable(z1), softmax_stable(z2))


11
[0.00247875 0.00673795 1.         0.01831564]
20000.0
[0. 0. 1.]
[0.00241233 0.00655741 0.97320538 0.01782488] [0. 0. 1.]


### Problem 3

In this problem, we work with one of the datasets included in the sklearn package called ''diabetes''. This dataset consists of 10 measurements taken from diabetes patients.

In [ ]:
import numpy as np 
from sklearn import datasets 

diabetes = datasets.load_diabetes()
X, y = diabetes.data, diabetes.target

Find/confirm the number of samples and features using ''.shape'' attribute of NumPy arrays.

In [ ]:
np.shape(X)

Thus, we have 442 samples with 10 features.

In [ ]:
np.shape(y)

Once again confirming that we have 442 data samples.

In [ ]:
diabetes.feature_names

Convert the input NumPy array X to a Pandas DataFrame. You can find feature names (i.e., column names) by using diabetes (we don't have access to row labels or patients').feature_names. Print the first 5 rows of the created DataFrame. 

In [ ]:
import pandas as pd


In [ ]:
print(type(X))

Thus, we can currently see that the input array X is currently a NumPy array. We are wanting to convert it from a NumPy array to a Pandas DataFrame.

In [ ]:
X_pd = pd.DataFrame(X, columns = ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'])

In [ ]:
print(type(X_pd))

Hence, we have converted the input NumPy array X from a Pandas DataFrame into a Pandas DataFrame.

In [ ]:
# Obtaining the first 5 rows of the newly created DataFrame
df_first_5 = X_pd.head(5)
df_first_5